#Время между дропами
interval: 1200
#Максимальное расстояние до дропа от спавна в мире
distance: 10000
#Имя сундука с аирдропом
name: AirDrop
#Шанс появления предмета в слоте(от 0 до 1)
chance: 0.25

#Предмет в случае, если список возможных предметов пуст
empty:
  #Имя предмета
  name: 'Array is empty'
  #Описание предмета
  description:
    - 'lore 1'
    - 'lore 2'
    - 'lore 3'
#Сообщения
messages:
  #Аирдроп заспавнен
  spawned: Заспавнен Аирдроп на координатах
  #Успешное добавление предмета в аирдроп
  addSuccess: Предмет успешно добавлен в аирдроп
  addFailed: Произошла ошибка при добавлении предмета в аирдроп
  removeSuccess: Предмет успешно удалён из аирдропа
  removeFailed: Произошла ошибка при удалении предмета из аирдропа
  clearSuccess: Аирдроп успешно очищен
  clearFailed: Произошла ошибка при очистке аирдропа
